language: node_js
node_js:
<<<<<<< .merge_file_fwWNiY
    - "8"
    - "9"
    - "10"
    - "11"
env:
    - CXX=g++-4.8
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
=======
  - "4.1"
  - "4.0"
  - "5"
  - "6"
  - "7"
  - "8"
>>>>>>> .merge_file_hLS0JD
before_script:
    - npm i -g typescript@next
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start
install:
    - npm install
    - npm run bootstrap
script:
    - npm run travis
after_script:
    - npm run coveralls

