version: "3"
services:
  test_runner:
    build:
      context: .
      dockerfile: e2e.Dockerfile
    depends_on:
      - ganache
      - geth
      - parity
  ganache:
    build:
      context: .
      dockerfile: ./e2e/docker/ganache.Dockerfile
  parity:
    build:
      context: .
      dockerfile: ./e2e/docker/parity.Dockerfile
  geth:
    build:
      context: .
      dockerfile: ./e2e/docker/geth.Dockerfile

networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16
