name: "Build"
on:
    push:
        branches:
            - "1.x"
        tags:
            - "*"
        paths-ignore:
            - "**.md"
            - "**.rst"
            - ".editorconfig"
            - ".gitignore"
            - ".npmignore"
            - "LICENSE"
    pull_request:
        types: [opened, reopened, synchronize]
        paths-ignore:
            - "**.md"
            - "**.rst"
            - ".editorconfig"
            - ".gitignore"
            - ".npmignore"
            - "LICENSE"
jobs:
    lint:
        runs-on: ubuntu-latest
        env:
            TEST: "build_and_lint"
        steps:
            - uses: actions/setup-node@v1
              with:
                  node-version: 12
            - uses: actions/checkout@v1
            - uses: actions/cache@v2
              with:
                  path: ~/.npm
                  key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
                  restore-keys: |
                      ${{ runner.os }}-node-
            - run: bash ./scripts/install.sh
            - run: bash ./scripts/ci.sh
    unit:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node: [8, 10, 11, 12, 13]
        env:
            TEST: "unit"
        steps:
            - uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node }}
            - uses: actions/checkout@v1
            - uses: actions/cache@v2
              with:
                  path: ~/.npm
                  key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
                  restore-keys: |
                      ${{ runner.os }}-node-
            - run: bash ./scripts/install.sh
            - run: bash ./scripts/ci.sh
    e2e:
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                testCmd:
                    [
                        "unit_and_e2e_clients",
                        "e2e_ganache",
                        "e2e_mosaic",
                        "e2e_browsers",
                    ]
        env:
            TEST: ${{ matrix.testCmd }}
            CI: true
            DISPLAY: :99.0
            PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: true
            SURGE_TOKEN: ${{ secrets.SURGE_TOKEN }}
            SURGE_LOGIN: ${{ secrets.SURGE_LOGIN }}
            BUNDLESIZE_GITHUB_TOKEN: ${{ secrets.BUNDLESIZE_GITHUB_TOKEN }}
        steps:
            - uses: actions/setup-node@v1
              with:
                  node-version: 12
            - uses: actions/checkout@v1
            - uses: actions/cache@v2
              with:
                  path: ~/.npm
                  key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
                  restore-keys: |
                      ${{ runner.os }}-node-
            - run: bash ./scripts/install.sh
            - run: bash ./scripts/ci.sh
            - name: Send coverage reports to Coveralls
              if: env.TEST == 'unit_and_e2e_clients'
              uses: coverallsapp/github-action@master
              with:
                  github-token: ${{ secrets.GITHUB_TOKEN }}
    e2e_windows:
        runs-on: windows-latest
        env:
            TEST: "e2e_windows"
            CI: true
        steps:
            - uses: actions/setup-node@v1
              with:
                  node-version: 12
            - uses: actions/checkout@v1
            - name: Get npm cache directory
              id: npm-cache
              run: |
                  echo "::set-output name=dir::$(npm config get cache)"
            - uses: actions/cache@v2
              with:
                  path: ${{ steps.npm-cache.outputs.dir }}
                  key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
                  restore-keys: |
                      ${{ runner.os }}-node-
            - run: bash ./scripts/install.sh
            - run: bash ./scripts/ci.sh
